name: 'dev'
version: '1.0.0'
profile: 'dev'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"



models:
  dev:
    staging:
      +enabled: true
      +materialized: table
    analytic:
      +enabled: true
      +materialized: table
    datamart:
      +enabled: true
      +materialized: view
